xebialabs/blueprint-cli

LICENCE.md

add a LICENCE.md

---

pkg/blueprint/blueprint_expressions.go
pkg/cloud/k8s/k8s_connector.go

D-20972 [Release] operator based upgrade from 10.0.0 to 22.0.0 fails

---

licenses/licences.md
pkg/blueprint/blueprint_expressions.go
pkg/cloud/k8s/k8s_connector.go
pkg/cloud/k8s/k8s_resource.go
pkg/osHelper/os_helper.go
pkg/util/util.go

S-87133 Improvements for xl op command and xl op check

---

pkg/cloud/k8s/k8s_resource.go

D-22667 Fix upgrade failure if resource was already deleted

---

pkg/cloud/k8s/k8s_resource.go
pkg/osHelper/os_helper.go
pkg/util/status.go

D-22662 Fix duplication of messages in cli output

---

pkg/blueprint/blueprints.go
pkg/models/blueprints.go

S-87888 Keep the generated yaml and answer files by default

---

pkg/blueprint/blueprints.go
pkg/models/blueprints.go

S-87974 xl kube improvements

---

pkg/cloud/k8s/k8s_resource.go

D-22667 During delete specially handle NotFound resources

---

build.gradle
go.mod
go.sum
licenses/licences.md
pkg/blueprint/blueprint_context.go
pkg/blueprint/blueprint_doc.go
pkg/blueprint/blueprints.go
pkg/blueprint/blueprints_test.go
pkg/cloud/k8s/k8s_resource.go

Upgrade survey lib

---

.gitignore
pkg/blueprint/blueprint_doc.go

D-23710 Missing questions in release installation

---

go.mod
go.sum

upgrade spinner lib

---

build.gradle
go.mod
go.sum

D-23859 Update go version to 1.19

---

pkg/blueprint/blueprint_doc.go

D-24325 Better error when storage class does not exist on cluster

---

build.gradle.kts
gradle.properties

S-97244 upgrade of gradle java

---

pkg/util/password_generator.go
pkg/util/password_generator_test.go

D-33478 - randPassword in the blueprints must generate valid passwords

---

pkg/util/password_generator.go
pkg/util/password_generator_test.go

D-33478 Random password should be generated with atleast one numeric, uppercase and lowercase character

---

build.gradle.kts

 S-107523 bump versions

---

build.gradle.kts

S-108427 Bump version

---

pkg/cloud/k8s/k8s_resource.go

S-109225 Saving kube config to file

---

pkg/cloud/k8s/k8s_resource.go

S-111480 add grace period option to the delete resources

---

build.gradle.kts
gradle.properties
pkg/blueprint/blueprint_context.go
pkg/blueprint/repository/zip/zip_repo.go

S-92289 add xl-cli -r flag to support custom zipped blueprints

---

pkg/blueprint/blueprint_doc.go
pkg/blueprint/blueprint_expressions.go
pkg/cloud/aws/aws_helper.go
pkg/cloud/k8s/k8s_connector.go

S-117147 Add warning in logs for AWS SDK support
